name: Evaluate

on:
    push:
       branches:
        - master
        - Release
    pull_request:
      branches:
        - master
        - Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Test Components
      working-directory: ./test/components.test/
      run: dotnet test --filter TestCategory=GithubAction
    - name: Relaese API
      working-directory: ./src/api/
      run: dotnet publish -c Release -o out
